### ISSUE TITLE
matrix dimensions must agree error in matlab

### ISSUE THREAD

**Issue by skyng22003** [SUwonglab/PECA#1]
Hi, I ran the example file and everything seems to work fine.

However, when I tried with my own samples I get an error in Matlab 

"matrix dimensions must agree"

the line of code that causes the error is 

Score=sqrt(TFExp*G').*(2.^abs(R2)).*full(BOH);

Removing .*(2.^abs(R2)) allows the line to execute without errors.

Any ideas as to where the problem might be?

Thanks,
Sky

**Comment by durenzn** [comment]
Thanks, In the case of your gene expression data don't include some TFs' expression, you will have this type of error. I have fixed this problem now, please try again.

Thanks
Zhana Duren

**Comment by skyng22003** [comment]
Thanks a lot for fixing the issue it now runs with no errors.

Thanks,
Sky
