### ISSUE TITLE
Remove assumption MATLAB is loaded via `Lmod`

### ISSUE THREAD

**Issue by t-silvers** [SUwonglab/PECA#16]
`PECA`'s shell scripts assume `Lmod` is installed and that MATLAB is available via `Lmod` in a module named `matlab`. See e.g. [here](https://github.com/SUwonglab/PECA/blob/2e0c17c5b8030bf065dafb5d69cf7762f8768394/PECA.sh#L70).

This info is missing from the documentation, but this dependency/assumption should in any case be removed.

**Comment by t-silvers** [comment]
Hi @durenzn, bumping this for when you have the chance to take a look.

**Comment by durenzn** [comment]
Thanks. This has been removed.

**Comment by t-silvers** [comment]
I've closed, but a note should be added to the `Run PECA` section of the `README`, saying something about it being assumed that `matlab` is in the user's `PATH`
