### ISSUE TITLE
Does PECA work for uncommon animal species?

### ISSUE THREAD

**Issue by hfyuanuq** [SUwonglab/PECA#3]
Hi, 
I read this paper "Modeling gene regulation from paired expression and chromatin accessibility data" and found this software will be very helpful for my research. My research organism is __Amphimedon queenslandica__ (one kind of demosponge). I have the ATAC-Seq data and RNA-seq data. We have the genome and genome feature formate files. I want to know how could I use PECA for my analysis? I found this software only build in human and mm information. 
Thanks for any useful information advance. 

Best Regards
Huifang

**Comment by durenzn** [comment]
The current version of the software is just designed for human and mouse. But the method could be used in other species. To apply this method, you need to construct a prior of RE-TG first. Once this prior is available, we can use the PECA method. In the future version, we will consider to include other species.

**Comment by durenzn** [comment]
> Hi,
> I read this paper "Modeling gene regulation from paired expression and chromatin accessibility data" and found this software will be very helpful for my research. My research organism is **Amphimedon queenslandica** (one kind of demosponge). I have the ATAC-Seq data and RNA-seq data. We have the genome and genome feature formate files. I want to know how could I use PECA for my analysis? I found this software only build in human and mm information.
> Thanks for any useful information advance.
> 
> Best Regards
> Huifang

The current version of the software is just designed for human and mouse. But the method could be used in other species. To apply this method, you need to construct a prior of RE-TG first. Once this prior is available, we can use the PECA method. In the future version, we will consider to include other species.
