### ISSUE TITLE
Can we use multi-cores to run the programme?

### ISSUE THREAD

**Issue by zifeng9527** [SUwonglab/PECA#4]
Thanks for your software.

I have a batch of Time Course ATAC and RNA-seq data to run.

Accordingly, i am running the PECA first. The motif finding step is too slow. I tried to add "-p 48" following -size given,  however, it seems not work.

**Comment by alexyfyf** [comment]
I've edited the `PECA.sh` file directly by adding `-p 12` and worked for me.
