### ISSUE TITLE
Error when running 'install.sh'

### ISSUE THREAD

**Issue by kevinqiu0** [SUwonglab/PECA#5]
Thanks for the software.

I'm currently having issues running the 'install.sh' script. Attempting to download the tar.gz file from your website returns a 403 Forbidden error. It looks like the entire website has access permissions removed completely. Full error below:

--2021-10-06 18:42:01--  http://web.stanford.edu/~zduren/PECA/Thresholding-Based%20SVD_files/Prior.tar.gz
Resolving web.stanford.edu (web.stanford.edu)... 171.67.215.200, 2607:f6d0:0:925a::ab43:d7c8
Connecting to web.stanford.edu (web.stanford.edu)|171.67.215.200|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-10-06 18:42:01 ERROR 403: Forbidden.

tar (child): Prior.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Thank you!

**Comment by durenzn** [comment]
Thanks for the comment. The webserver of Prior data had some problem and we have moved it to GitHub. This problem has been solved,
