### ISSUE TITLE
Question: Do you suggest filtering the input gene expression table before running PECA

### ISSUE THREAD

**Issue by alexyfyf** [SUwonglab/PECA#6]
Hi team,

I read in the manuscript you mentioned building the network considering only genes with FPKM > 10. 
So do you suggest removing lowly expressed genes before running PECA? 
In addition, I noticed in your `/Prior/TFTG_corr_mouse.mat`, there is no Trp53 for mouse `TFName`, just want to know how you defined these TFs?

Thanks.

**Comment by durenzn** [comment]
Selecting gene with FPKM > 10 is to generate a tissue specific network in the original PECA paper. This software is PECA2 and which is different from the method  used to generate tissue specific network in PECA (2017) paper. So you do not remove low expressed genes. For some reason, we missed three TFs Trp53, Trp63, and Trp73. We have added these TFs to our latest version. Thank you for your comment.
