### ISSUE TITLE
Question: should I use only nucleosome free region as ATACseq input?

### ISSUE THREAD

**Issue by ftucos** [SUwonglab/PECA#9]
Hi, I was wondering if filtering the ATACseq bam file used as input for PECA2 to retain only Nucleosome Free Regions is required and or would increase the accuracy of the analysis.

**Comment by durenzn** [comment]
Interesting question, we never tried this before. My guess is that using whole bam file is better because a local normalization is used in PECA.

**Comment by ftucos** [comment]
Thank you very much for your feedback.
Maybe I'll try both and I'll let you know if I observe relevant differences.
